---
abstract: 'A libcurl based HTTP backend for ElasticSearch'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  ElasticSearch::SearchBuilder: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ElasticSearch-Transport-Curl
requires:
  ElasticSearch: 0.60
  ElasticSearch::Transport: 0
  Encode: 0
  WWW::Curl::Easy: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/clintongormley/ElasticSearch-Curl/issues
  homepage: https://metacpan.org/module/ElasticSearch
  repository: git://github.com/clintongormley/ElasticSearch-Curl.git
version: 0.05
